### ISSUE TITLE
1.0 Todo

### ISSUE THREAD

**Issue by mouse0w0** [Mouse0w0/WowCommon#4]
Easy to implement:
- [x] Custom key binding
- [ ] Custom GUI and HUD
- [ ] Visual editor for developer and server owner
- [ ] Custom music
- [ ] Advanced chat UI

Hard to implement:
- [ ] Custom item/block/entity/armor/tileentity model and texture
- [ ] Custom render script
- [ ] Remote script
- [ ] In-game website browser (JCEF)
- [ ] Offline map
- [ ] Game overlay

Deprecated:
- ~Client cookie API~[Reason: Unsafe]
